#!/bin/sh
# Creates what the reference deployment needs and git must never hold:
#   <dir>/secrets/ca.pem, ca.key       a private CA for MongoDB's certificate
#   <dir>/secrets/mongo/               MongoDB's certificate, the CA and the
#                                      replica set's key file
#   <dir>/secrets/tls/edge.crt, .key   a self-signed certificate for nginx:
#                                      replace it with a real one
#   <dir>/secrets/metrics-token        the token Prometheus scrapes with
#   <dir>/.env                         random passwords and settings
# <dir> defaults to this script's directory. Existing files are kept, so
# running it again is safe. Needs openssl.
#
#   ./setup.sh [dir]
#   SERVER_NAME=api.example.com ./setup.sh
set -eu
here=$(cd "$(dirname "$0")" && pwd)
dir=${1:-$here}
server_name=${SERVER_NAME:-localhost}
secrets=$dir/secrets
mkdir -p "$secrets/mongo" "$secrets/tls"
umask 077

if [ ! -f "$secrets/ca.key" ]; then
  openssl req -x509 -newkey rsa:3072 -nodes -days 3650 -subj "/CN=backd internal CA" \
    -keyout "$secrets/ca.key" -out "$secrets/ca.pem" 2>/dev/null
  chmod 644 "$secrets/ca.pem" # a certificate, not a secret: clients need it
  echo "created $secrets/ca.pem (keep ca.key offline in production)"
fi

# issue <name> <subject CN> <subjectAltName> <out prefix> [<extendedKeyUsage>]:
# a certificate signed by the CA (serverAuth unless given).
issue() {
  openssl req -newkey rsa:2048 -nodes -subj "/CN=$2" -keyout "$4.key" -out "$4.csr" 2>/dev/null
  printf 'subjectAltName=%s\nextendedKeyUsage=%s\n' "$3" "${5:-serverAuth}" > "$4.ext"
  openssl x509 -req -in "$4.csr" -CA "$secrets/ca.pem" -CAkey "$secrets/ca.key" -CAcreateserial \
    -days 825 -extfile "$4.ext" -out "$4.crt" 2>/dev/null
  rm -f "$4.csr" "$4.ext"

}

if [ ! -f "$secrets/mongo/mongo.pem" ]; then
  # clientAuth too: replica set members connect to each other (and a single
  # member to itself, e.g. to vote on index builds) presenting this certificate.
  issue mongo mongo "DNS:mongo,DNS:localhost" "$secrets/mongo/mongo" serverAuth,clientAuth
  cat "$secrets/mongo/mongo.crt" "$secrets/mongo/mongo.key" > "$secrets/mongo/mongo.pem"
  rm -f "$secrets/mongo/mongo.crt" "$secrets/mongo/mongo.key"
  cp "$secrets/ca.pem" "$secrets/mongo/ca.pem"
  echo "created $secrets/mongo/mongo.pem"
  # mongod runs as uid 999 in its container and must read the key. In
  # production, prefer `chown 999 mongo.pem` and mode 600.
  chmod 644 "$secrets/mongo/mongo.pem" "$secrets/mongo/ca.pem"
  chmod 755 "$secrets/mongo"
fi

if [ ! -f "$secrets/mongo/keyfile" ]; then
  # Authenticates the replica set's members to each other. mongod gets a
  # private copy at start (see compose.yaml); here only this user reads it.
  openssl rand -base64 756 > "$secrets/mongo/keyfile"
  chmod 600 "$secrets/mongo/keyfile"
  echo "created $secrets/mongo/keyfile"
fi

if [ ! -f "$secrets/minio/public.crt" ]; then
  # The object storage (a realm's files): its certificate, signed by the same
  # CA. backd trusts that CA through SSL_CERT_FILE (see compose.yaml). MinIO
  # reads public.crt, private.key and the CAs it should trust from one folder.
  mkdir -p "$secrets/minio/CAs"
  issue minio minio "DNS:minio,DNS:localhost" "$secrets/minio/minio"
  mv "$secrets/minio/minio.crt" "$secrets/minio/public.crt"
  mv "$secrets/minio/minio.key" "$secrets/minio/private.key"
  cp "$secrets/ca.pem" "$secrets/minio/CAs/ca.pem"
  chmod 755 "$secrets/minio" "$secrets/minio/CAs"
  chmod 644 "$secrets/minio/public.crt" "$secrets/minio/private.key" "$secrets/minio/CAs/ca.pem"
  echo "created $secrets/minio/public.crt"
fi

if [ ! -f "$secrets/tls/edge.key" ]; then
  issue edge "$server_name" "DNS:$server_name,DNS:localhost,IP:127.0.0.1" "$secrets/tls/edge"
  chmod 755 "$secrets/tls"
  chmod 644 "$secrets/tls/edge.crt"
  echo "created $secrets/tls/edge.crt (self-signed: replace it with a real certificate)"
fi

if [ ! -f "$dir/.env" ]; then
  pw() { openssl rand -hex 24; }
  cat > "$dir/.env" <<ENV
# Generated by setup.sh. Keep it secret; never commit it.
SERVER_NAME=$server_name
MONGO_ROOT_PASSWORD=$(pw)
BACKD_APP_PASSWORD=$(pw)
BACKD_BACKUP_PASSWORD=$(pw)
SECRETS_DIR=$secrets
# age public key(s) that backups are encrypted to, separated by spaces.
# Create the key pair away from this server (age-keygen -o backup-identity.txt)
# and keep the private key offline. Backups refuse to run without it.
BACKUP_RECIPIENTS=
# Functions: shared secrets between backd, the executor, egress and the
# worker (see the docs, Functions -> "Running in production"). BACKD_SECRETS_KEY additionally decrypts every function
# secret ever stored (docs: Functions -> Secrets): back it up separately
# from database backups (see Operations -> Backup and restore), never
# alongside them, or a leaked backup and its own encryption defeat each
# other.
BACKD_EXECUTOR_TOKEN=$(pw)
BACKD_CALLBACK_KEY=$(pw)
BACKD_EGRESS_KEY=$(pw)
BACKD_SECRETS_KEY=$(pw)
# Metrics (docs: Operations -> Metrics): the token every backd process asks
# for on its private metrics port, and Prometheus presents.
BACKD_METRICS_TOKEN=$(pw)
ENV
  echo "created $dir/.env"
fi
if ! grep -q '^MINIO_ROOT_PASSWORD=' "$dir/.env"; then
  # The object storage (see compose.yaml): the root password is only for the
  # setup job; backd's own key can use one bucket and nothing else.
  printf '# Object storage (docs: Files): the setup job creates the bucket and backd'"'"'s key; the realm'"'"'s\n# secrets STORAGE_ACCESS_KEY and STORAGE_SECRET_KEY hold the key (backd secret set).\nMINIO_ROOT_PASSWORD=%s\nSTORAGE_ACCESS_KEY=backd-files\nSTORAGE_SECRET_KEY=%s\n' "$(openssl rand -hex 24)" "$(openssl rand -hex 24)" >> "$dir/.env"
  echo "added the object storage settings to $dir/.env"
fi
if ! grep -q '^BACKD_METRICS_TOKEN=' "$dir/.env"; then
  # An .env from before metrics existed.
  printf '# Metrics token (see Operations -> Metrics).\nBACKD_METRICS_TOKEN=%s\n' "$(openssl rand -hex 24)" >> "$dir/.env"
  echo "added BACKD_METRICS_TOKEN to $dir/.env"
fi
if [ ! -f "$secrets/metrics-token" ]; then
  # Prometheus reads the token from a file. It runs as uid 65534 and must
  # read it; in production, prefer `chown 65534` and mode 600.
  sed -n 's/^BACKD_METRICS_TOKEN=//p' "$dir/.env" | tr -d '\n' > "$secrets/metrics-token"
  chmod 644 "$secrets/metrics-token"
  echo "created $secrets/metrics-token"
fi
