package functions

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/fernandezvara/backd/internal/registry"
)

// JSDocTypes generates JSDoc typedefs from every function's input and
// output JSON Schemas (`backd functions types`), for editor autocomplete
// on ctx.input and the return value. A function without a schema, or
// whose schema can't be read or parsed, is skipped (with a comment
// explaining why for the latter): this never fails outright, so the
// command always produces something to paste into an editor.
func JSDocTypes(reg *registry.Registry) string {
	dbs := reg.Databases()
	sort.Slice(dbs, func(i, j int) bool {
		if dbs[i].Realm != dbs[j].Realm {
			return dbs[i].Realm < dbs[j].Realm
		}
		return dbs[i].Name < dbs[j].Name
	})
	var b strings.Builder
	b.WriteString("// Generated by `backd functions types`. Paste into your editor for\n// autocomplete on ctx.input and a function's return value.\n\n")
	before := b.Len()
	for _, db := range dbs {
		if db.Functions == nil {
			continue
		}
		names := make([]string, 0, len(db.Functions.Functions))
		for name := range db.Functions.Functions {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			writeFunctionTypes(&b, db.Realm, db.Name, name, db.Functions.Functions[name].Dir)
		}
	}
	if b.Len() == before {
		b.WriteString("// no function declares an input or output schema\n")
	}
	return b.String()
}

// writeFunctionTypes appends one function's typedefs (input, output, or
// both) to b. A function with neither schema writes nothing.
func writeFunctionTypes(b *strings.Builder, realm, database, name, dir string) {
	in, inErr := readSchema(filepath.Join(dir, registry.InputSchemaFile))
	out, outErr := readSchema(filepath.Join(dir, registry.OutputSchemaFile))
	if in == nil && out == nil && inErr == nil && outErr == nil {
		return
	}
	fmt.Fprintf(b, "// %s/%s/%s\n", realm, database, name)
	base := pascal(realm) + pascal(database) + pascal(name)
	for _, s := range []struct {
		suffix string
		schema any
		err    error
	}{{"Input", in, inErr}, {"Output", out, outErr}} {
		switch {
		case s.err != nil:
			fmt.Fprintf(b, "// %s schema: %v\n", strings.ToLower(s.suffix), s.err)
		case s.schema != nil:
			fmt.Fprintf(b, "/** @typedef {%s} %s%s */\n", jsdocType(s.schema, 0), base, s.suffix)
		}
	}
	b.WriteByte('\n')
}

// readSchema reads and parses a schema file; (nil, nil) when it doesn't exist.
func readSchema(path string) (any, error) {
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var v any
	if err := json.Unmarshal(data, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// maxTypeDepth stops recursion on a pathological or self-referential
// schema; JSON Schema's $ref isn't resolved here, so this is a guard
// rail, not expected to trigger on well-formed schemas.
const maxTypeDepth = 6

// jsdocType renders one JSON Schema node as a Closure/JSDoc type expression.
func jsdocType(schema any, depth int) string {
	m, ok := schema.(map[string]any)
	if !ok {
		return "*"
	}
	if enum, ok := m["enum"].([]any); ok && len(enum) > 0 {
		parts := make([]string, len(enum))
		for i, v := range enum {
			parts[i] = literal(v)
		}
		return strings.Join(parts, "|")
	}
	switch t := m["type"].(type) {
	case string:
		return primitive(t, m, depth)
	case []any:
		var parts []string
		for _, v := range t {
			if s, ok := v.(string); ok {
				parts = append(parts, primitive(s, m, depth))
			}
		}
		if len(parts) == 0 {
			return "*"
		}
		return strings.Join(parts, "|")
	}
	if _, ok := m["properties"]; ok {
		return primitive("object", m, depth)
	}
	return "*"
}

func literal(v any) string {
	data, err := json.Marshal(v)
	if err != nil {
		return "*"
	}
	return string(data)
}

func primitive(t string, m map[string]any, depth int) string {
	switch t {
	case "string":
		return "string"
	case "integer", "number":
		return "number"
	case "boolean":
		return "boolean"
	case "null":
		return "null"
	case "array":
		if depth >= maxTypeDepth {
			return "Array"
		}
		return "Array<" + jsdocType(m["items"], depth+1) + ">"
	case "object":
		return objectType(m, depth)
	default:
		return "*"
	}
}

func objectType(m map[string]any, depth int) string {
	props, _ := m["properties"].(map[string]any)
	if len(props) == 0 {
		return "Object<string, *>"
	}
	if depth >= maxTypeDepth {
		return "Object"
	}
	required := map[string]bool{}
	if req, ok := m["required"].([]any); ok {
		for _, r := range req {
			if s, ok := r.(string); ok {
				required[s] = true
			}
		}
	}
	names := make([]string, 0, len(props))
	for name := range props {
		names = append(names, name)
	}
	sort.Strings(names)
	parts := make([]string, 0, len(names))
	for _, name := range names {
		opt := ""
		if !required[name] {
			opt = "="
		}
		data, _ := json.Marshal(name)
		parts = append(parts, fmt.Sprintf("%s: %s%s", string(data), jsdocType(props[name], depth+1), opt))
	}
	return "{" + strings.Join(parts, ", ") + "}"
}

// pascal turns a lower-case, hyphen/underscore-separated config name (a
// realm, database or function name, per registry.ValidName) into a
// PascalCase identifier segment.
func pascal(s string) string {
	var b strings.Builder
	upper := true
	for _, r := range s {
		switch {
		case r == '-' || r == '_':
			upper = true
		case upper && r >= 'a' && r <= 'z':
			b.WriteRune(r - 'a' + 'A')
			upper = false
		default:
			b.WriteRune(r)
			upper = false
		}
	}
	return b.String()
}
